#!/bin/bash
#
# shortcuts for behemoth commands
# assumes that mvn clean install has been called succesfully

# if no args specified, show usage
if [ $# = 0 ]; then
  echo "Usage: behemoth COMMAND"
  echo "where COMMAND is one of:"
  echo "  corpusreader             blablabla"
  echo "  corpusfilter            blablabla"
  echo "Most commands print help when invoked w/o parameters."
  exit 1
fi

# get arguments
COMMAND=$1
shift



# figure out which class to run
if [ "$COMMAND" = "corpusreader" ] ; then
  CLASS=com.digitalpebble.behemoth.util.CorpusReader
  MODULE=core
elif [ "$COMMAND" = "corpusfilter" ] ; then
  CLASS=com.digitalpebble.behemoth.util.CorpusFilter
  MODULE=core
else
   echo "unknown command"
   exit -1;
fi

# distributed mode
BEHE_JOB=$MODULE/target/behemoth-$MODULE-1.0-SNAPSHOT-job.jar
EXEC_CALL="hadoop jar $BEHE_JOB"

# check that hadoop can be found on the path
if [ $(which hadoop | wc -l ) -eq 0 ]; then
    echo "Can't find Hadoop executable. Add HADOOP_HOME/bin to the path"
    exit -1;
fi

# run it
exec $EXEC_CALL $CLASS "$@"


